# Generated by Django 3.0 on 2019-12-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20191208_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='spot',
            field=models.CharField(max_length=255),
        ),
    ]
